config/routes.rb
Rails.application.routes.draw do

  # root 'home#index'
  root 'drawings#index'

  get 'login', to: 'access#login'
  post 'access/attempt_login'
  get 'logout', to: 'access#logout'

  resources :users
  resources :abouts
  resources :contacts
  resources :categories
  resources :images
  resources :drawings

  resources :drawings do
    resources :images
  end


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/partials/_drawings_index_table.html.erb
<p id="notice"><%= notice %></p>
<div class='row justify-content-md-center'>
  <div class='col-lg-10 col-md-10 col-sm-10'>
    <%= link_to 'novo desenho', new_drawing_path%>
    <table class="table">
      <thead>
        <tr>
          <th>Nome do desenho</th>
          <th>Categoria</th>
          <th colspan="3"></th>
        </tr>
      </thead>
      <tbody>
        <% @drawings_all.each do |drawing| %>
          <tr>
            <td><%= link_to drawing.title, drawing_path(drawing)  %></td>
            <td><%= drawing.category.name %></td>
            <td><%= link_to 'add images', new_drawing_path(drawing) %></td>
            <td><%= link_to 'deletar', drawing, method: :delete, data: { confirm: 'isso vai fazer com que todos os desenhos sejam deletados junto, tem certeza?' } %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/partials/_footer.html.erb
<div class="row">
  <div class="col-lg-3 col-md-3 col-sm-6">
    <p> Copyright  2017 -
      <%- if logged?%>
        <%= link_to 'GerdaoArt', logout_path, :class =>"login-link"%>
      <%- else%>
        <%= link_to 'GerdaoArt', login_path, :class =>"login-link"%>
      <% end %>
    </p>
  </div>
  <div class="col-lg-7 col-md-7"></div>
  <div class="col-lg-2 col-md-2 col-sm-6">
    <%= render 'partials/social_midia'%>
  </div>
</div>

app/views/partials/_navbar.html.erb
<div class="row justify-content-center">
  <div class="col-lg-3 col-md-3">
    <h3>
      <%= link_to 'Gerda & Art', root_url, class:"gerdao-title"%>
    </h3>
  </div>
</div>

<div class="row justify-content-start">
  <div class="col-lg-2 col-md-2 col-sm-12">
    <%= render partial: 'partials/social_midia' %>
  </div>
  <div class="col-lg-8 col-md-8 col-sm-12">
    <div class="main-menu">
      <a><%= link_to 'images', drawings_path, class: "main-menu" %></a>
      <a><%= link_to 'about', abouts_path, class: "main-menu"%></a>
      <a><%= link_to 'contact', contacts_path, class: "main-menu" %></a>
    </div>
  </div>
</div>

app/views/partials/_social_midia.html.erb
<a href= "https://www.facebook.com/gerdaoart/">
  <i class="fa fa-facebook-square fa-2x" aria-hidden="true"></i>
</a>
<a href="http://www.imgsta.com/user/gerdaoart">
  <i class="fa fa-instagram fa-2x" aria-hidden="true"></i>
</a>
<a>
  <i class="fa fa-pinterest-square fa-2x" aria-hidden="true"></i>
</a>
<a>
  <i class="fa fa-twitter-square fa-2x" aria-hidden="true"></i>
</a>
<a href="https://gerdaoart.tumblr.com/">
  <i class="fa fa-tumblr-square fa-2x" aria-hidden="true"></i>
</a>