config/routes.rb
Rails.application.routes.draw do

  # root 'home#index'
  root 'drawings#index'

  get 'login', to: 'access#login'
  post 'access/attempt_login'
  get 'logout', to: 'access#logout'

  resources :users
  resources :abouts
  resources :contacts
  resources :categories
  resources :images
  resources :drawings

  resources :drawings do
    resources :images
  end


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/about.rb
class About < ApplicationRecord
end

app/controllers/abouts_controller.rb
class AboutsController < ApplicationController
  before_action :set_about, only: [:show, :edit, :update, :destroy]
  before_action :has_access?, except: [:index, :show]


  def index
    @abouts_pinned = About.where(pinned: true).order(:created_at)
    @abouts_not_pinned = About.where(pinned: false).order(created_at: :desc)
  end

  def show
  end

  def new
    @about = About.new
  end

  def edit
  end

  def create
    @about = About.new(about_params)
    if @about.url_title == nil or @about.url_title == ""
      @about.url_title = "Check it here."
    end

    if @about.valid?
      @about.save
      redirect_to abouts_url, notice: 'About was successfully created.'
    else
      render :new
    end
  end

  def update
    if @about.update(about_params)
      if @about.url_title == nil or @about.url_title == ""
        @about.url_title = "Check it here."
        @about.save
      end
      redirect_to abouts_url, notice: 'About was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @about.destroy
    redirect_to abouts_url, notice: 'About was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_about
      @about = About.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def about_params
      params.require(:about).permit(:body, :pinned, :url_address, :url_title)
    end
end

app/helpers/abouts_helper.rb
module AboutsHelper
end

app/views/abouts/_form.html.erb
<%= simple_form_for about , html: {class: 'form-horizontal'} do |f| %>
  <%= f.error_notification%>
  <%= f.input :body, as: :text %>
  <%= f.input :pinned, label:"Fixar no Topo"%>
  <%= f.input :url_address, as: :string, label:"URL (caso tenha)"%>
  <%= f.input :url_title, as: :string, label:"Titulo do link (caso tenha)"%>

  <%= f.button :submit %>

<% end %>

app/views/abouts/edit.html.erb
<h3>Editing About</h3>

<%= render 'form', about: @about %>

<%= link_to 'Back', abouts_path %>

app/views/abouts/index.html.erb
<p id="notice"><%= notice %></p>

<div >
  <%- @abouts_pinned.each do |about| %>
    <p class="pinned-about"><%= about.body %></p>
    <%- if logged? %>
      <p>
        <%= link_to 'editar', edit_about_path(about)%>
        /
        <%= link_to 'deletar', about, method: :delete, data: { confirm: 'Are you certain? Tem certeza de que quer fazer isso?'}%>
      </p>
    <% end %>
  <% end %>
</div>
<div class="row">
  <%- @abouts_not_pinned.each do |about| %>
    <div class="col-md-6 col-lg-6 col-sm-12">
      <p class="not-pinned-about">
        <%= about.created_at.strftime("%d/%b/%y")%>
        <br/>
        <%= about.body %>
        <%- if about.url_address != nil%>
          <br/> - <br/>
          <%= link_to about.url_title, "#{about.url_address}" %>
        <% end %>
      </p>
      <%- if logged? %>
        <p>
          <%= link_to 'editar', edit_about_path(about)%>
          /
          <%= link_to 'deletar', about, method: :delete, data: { confirm: 'Are you certain? Tem certeza de que quer fazer isso?'}%>
        </p>
      <% end %>
    </div>
  <% end %>
</div>


<%= link_to 'Criar About', new_about_path if logged?%>

app/views/abouts/new.html.erb
<h3>About</h3>

<%= render 'form', about: @about %>

<%= link_to 'voltar', abouts_path %>

app/views/abouts/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_about_path(@about) %> |
<%= link_to 'Back', abouts_path %>